version: '3.8'
services:
  mongodb:
    image: 'mongo'
    env_file:
      - ./env/mongo.env
    volumes: 
      - ./data:/data/db
  backend:
    build: ./backend
    ports:
      - '80:80'
    volumes:
      - ./logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    ports: 
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend


  #KEY = KEYS DID NOT WORK FOR MY DOCKER COMPOSE FILE
#volumes:
  #data:
  #logs: